### ISSUE TITLE
Chrome download gone

### ISSUE THREAD

**Issue by Rarst** [nathan-osman/Stack-Alert#13]
http://quickmediasolutions.com/stackalert/stackalert.crx leads to 404

**Comment by pushpesh4u** [comment]
So does http://quickmediasolutions.com/stackalert/stackalert.xpi

**Comment by lizhenguo** [comment]
why?

**Comment by nathan-osman** [comment]
I finally got around to fixing this. The files are here now:

- http://files.quickmediasolutions.com/stackalert/stackalert.crx (Chrome)
- http://files.quickmediasolutions.com/stackalert/stackalert.oex (Opera)
- http://files.quickmediasolutions.com/stackalert/stackalert.xpi (Firefox)

I have no idea if the Firefox or Opera builds work. They have not been tested. The Chrome one works. I'll update the README shortly.
